project:
  type: website
  output-dir: docs

website:
  title: "hubungin"
  navbar:
    left:
      - href: index.qmd
        text: Materi
      - about.qmd

format:
  html:
    theme: beige
    css: styles.css
    toc: true



