---
title: "Deskripsi Mata Kuliah"
---

Mata kuliah Hubungan Industrial/EKMA 4367 merupakan lanjutan dari mata kuliah Manajemen Sumber Daya Manusia (MSDM). Melalui mata kuliah ini, Anda akan dapat memahami konsep, dasar Hubungan Industrial, struktur di dalam Hubungan Industrial termasuk di dalamnya Serikat Pekerja, proses di dalam praktik Hubungan Industrial khususnya mengenai perjanjian kerja bersama, isu mengenai biaya kontrak perburuhan yang berhubungan dengan pemberian penghargaan penyelesaian konflik serta praktik Hubungan Industrial di dalam kerangka hukum ketenagakerjaan di Indonesia. 

Mata kuliah ini dirancang untuk membekali Anda dengan teori dan praktik ketenagakerjaan di Indonesia yang menjadi faktor kunci dalam penyelesaian permasalahan ketenagakerjaan dalam suatu organisasi.

Setelah mempelajari mata kuliah Hubungan Industrial, Anda diharapkan memiliki pengetahuan yang komprehensif tentang konsep dasar, struktur dan proses Hubungan Industrial dalam kerangka hukum ketenagakerjaan di Indonesia. Secara lebih khusus, setelah mempelajari mata kuliah ini Anda diharapkan akan mampu menjelaskan: 

1. konteks hubungan industrial secara umum dan keterkaitan hubungan industrial dengan berbagai bidang ilmu lain;  
2. serikat pekerja dan praktik serikat pekerja di Indonesia; 
3. perjanjian kerja bersama dan negosiasi perjanjian. Indonesia; 
4. pemberian penghargaan kepada karyawan dan isu gaji, upah dan tunjangan; 
5. konflik dan penyelesaian perselisihan hubungan industrial di tempat kerja; 
6. praktik hubungan industrial, perkembangan dan praktik hukum ketenagakerjaan di Indonesia

Mata kuliah Hubungan Industrial, yakni 2 sks maka materi mata kuliah ini disajikan 
dalam 6 modul, yang disusun sebagai berikut:

- Modul 1.  Karakteristik dan Konteks Hubungan Industrial  
- Modul 2.  Serikat Pekerja 
- Modul 3.  Perjanjian Kerja Bersama dan Negosiasi Perjanjian 
- Modul 4.  Biaya Kontrak Perburuhan 
- Modul 5.  Konflik dan Penyelesaian Perselisihan Hubungan Industrial 
- Modul 6.  Praktik Hubungan Industrial di Indonesia 

Buku Rujukan:

* Ariani, Dorothea Wahyu (2014). Hubungan Industrial EKMA4367. Tangerang Selatan: Universitas Terbuka.
* Frege, Carola and John Kelly, (2020). Comparative Employment Relations in the Global Economy. Routledge.
* Robbins, S. P. (2017). Organizational Behaviour 9th edition. Pearson Education Limited