---
title: "Serikat Pekerja"
author: "Tedy Herlambang"
format: 
  revealjs:
    theme: blood
    chalkboard: 
      theme: chalkboard
---

## KONSEP SERIKAT PEKERJA (1)

- Serikat pekerja menunjukkan hubungan karyawan sehari-hari dengan pengusaha atau majikan, atau pemilik perusahaan.
- Pembentukan serikat pekerja merupakan upaya mengadakan perbaikan secara bersama – sama. 
- Pembentukan serikat pekerja: kohesivitas kelompok, kesadaran masuk dalam suatu kelas, dan ancaman eksternal.

## KONSEP SERIKAT PEKERJA (2)

- Serikat pekerja harus didirikan secara demokratis dengan tujuannya memberikan perlindungan, pembelaan hak dan kepentingan, serta meningkatkan kesejahteraan pekerja dan keluarganya. 
- Dalam mencapai tujuan dan melaksanakan hak dan kewajibannya, serikat pekerja bertanggung jawab kepada anggota, masyarakat, dan negara

## TEORI YANG MENDASARI SERIKAT PEKERJA (1)

- Teori Kemakmuran Umum: perjuangan serikat pekerja untuk meningkatkan upah dapat mendorong & memperkuat pertumbuhan ekonomi
- Teori Pemasaran Tenaga Kerja: kondisi di tempat para pekerja itu bekerja ditentukan oleh kekuatan dan pengaruh pekerja di pasar dan tenaga kerja
- Teori Produktivitas: Upah ditentukan oleh produktivitas karyawan. Semakin tinggi produktivitas maka upah akan semakin tinggi pula 

## TEORI YANG MENDASARI SERIKAT PEKERJA (2)

- Teori Perundingan/ Tawar-Menawar: Pasar tenaga kerja ditentukan oleh kekuatan ekonomi yang berlawanan dari karyawan dan pengusaha
- Teori Oposisi Loyal Terhadap Manajemen: Serikat pekerja harus menolak tanggung jawab atas manajemen dan tidak mau menjadi manajer.

## TANGGUNG JAWAB & WEWENANG SERIKAT PEKERJA (1)

- KEAMANAN PERSERIKATAN: Ada beberapa tahap pengakuan pengusaha terhadap serikat pekerja yaitu; anti union shop, open shop, exclusive bargaining agent, preferential shop, maintenance of membership, Agency shop, union shop, closed shop, dan check off. 
- SARANA MENGHADAPI PENGUSAHA: Ada tiga hal yang menjadi perhatian serikat pekerja yaitu pemogokan, pemagaran, dan pemboikotan

## TANGGUNG JAWAB & WEWENANG SERIKAT PEKERJA (2)

- PENGENDALIAN & DISIPLIN INTERNAL: Anggaran dasar serikat pekerja memberi kekuasaan kepda pengurus serikat pekerja untuk bertindak terhadap anggotanya yang menentang pimpinan atau menolak mentaati persyaratan dalam perjanjian atau kesepakatan kerja bersama.

## FUNGSI SERIKAT PEKERJA (1)

- Sebagai pihak dalam pembuatan perjanjian kerja bersama & penyelesaian perselisihan industrial
- Sebagai wakil karyawan/pekerja di bidang kerjasama ketenagakerjaan sesuai dengan tingkatan
- Sebagai sarana menciptakan hubungan industrial yang harmonis, dinamis, dan berkeadilan sesuai UU yang berlaku

## FUNGSI SERIKAT PEKERJA (2)

- Sebagai sarana penyalur aspirasi dalam memperjuangkan hak dan kepentingan anggotanya
- Sebagai perencana, pelaksana, dan penanggung jawab pemogokan karyawan/pekerja sesuai dengan peraturan UU yang berlaku

## KONSEP SERIKAT PEKERJA NASIONAL

- Berdasarkan UU No.21 tahun 2000, serikat pekerja/ serikat buruh merupakan organisasi yang dibentuk dari, oleh, dan untuk karyawan atau pekerja baik di dalam perusahaan maupun di luar perusahaan, yang bersifat bebas, terbuka, mandiri, demokratis, dan bertanggung jawab guna memperjuangkan, membela, serta melindungi hak dan kepentingan karyawan atau pekerja, serta meningkatkan kesejahteraan karyawan dan keluarganya. 

## PEMBENTUKAN SERIKAT PEKERJA

- Hak menjadi anggota serikat pekerja merupakan hak asasi karyawan yang telah dijamin di dalam Pasal 28 UUD 1945. 
- Konvensi ILO No.87 tentang Kebebasan Berserikat dan Perlindungan Hak untuk berorganisasi, dan Konvensi ILO No.98 tentang Hak untuk Berorganisasi dan Berunding Bersama sudah diratifikasi oleh Indonesia menjadi bagian dari peraturan perundang – undangan nasional, yaitu masing – masing dengan Keputusan Presiden No.80 tahun 1998, dan UU No.18 tahun 1956. 
- Kedua Konvensi tersebut menjamin hak pekerja untuk membentuk atau menjadi anggota serikat pekerja.

## KEANGGOTAAN SERIKAT PEKERJA

- Keanggotaan serikat pekerja terbuka, yaitu menerima anggota tanpa membedakan aliran politik, agama, suku bangsa dan jenis kelamin baik serikat pekerja atau serikat buruh, federasi dan konfederasi yang diatur dalam anggaran dasar dan anggaran rumah tangganya.
- Setiap federasi serikat pekerja atau serikat buruh hanya dapat menjadi anggota dari satu konfederasi serikat pekerja atau serikat buruh. Kebebasan untuk membentuk, masuk, atau tidak masuk menjadi anggota serikat pekerja merupakan salah satu hak dasar karyawan.

## PERKEMBANGAN SERIKAT PEKERJA DI INDONESIA (1)

- Nederland Indische Onderwijs Genootschap (NIOG) thn 1897
- Postbond di bidang pos thn 1905
- Suikerbond di perkebunan gula  thn 1906
- Cultuurbond di perkebunan karet  thn 1907 serta Vereniging Spoor en Tram Personeel (VSTP)

## PERKEMBANGAN SERIKAT PEKERJA DI INDONESIA (2)

- Budi Utomo thn 1902 
- Serikat Dagang Islam thn 1911 
- Partai Komunis Indonesia thn 1920
- Partai Nasional Indonesia thn 1927

## KEBIJAKAN PUBLIK & ORGANISASI INDUSTRIAL(1)

- Selama masa pertumbuhan industri, produksi adalah padat karya. 
- Karakteristik produk relatif berbeda. 
- Pilihan / referensi pelanggan dinyatakan oleh beberapa produsen sebagai hal yang berada di luar bisnis bila produk mereka tidak memenuhi kebutuhan pelanggan. 

## KEBIJAKAN PUBLIK & ORGANISASI INDUSTRIAL(2)

- Metode produksi terstandarisasi, modal dan karyawan yang lebih murah diganti oleh orang ahli, dan produsen yang lebih efisien menurunkan harga untuk mendapatkan pangsa pasar sehingga dapat mengendalikan produsen yang memiliki margin kecil. 
- Dari waktu ke waktu industri didominasi oleh beberapa perusahaan dan kurang dominan dalam kepemimpinan pasar.

---
<center> “SELAMAT BELAJAR, SEKIAN DAN TERIMA KASIH“</center>








